# Variables that contains the user credentials to access Twitter API
ACCESS_TOKEN = "XXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXX"
ACCESS_TOKEN_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
CONSUMER_KEY = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
CONSUMER_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# put your twitter handler name or hastag for search
handler_list =["@subhendu0005","@Subhendu__7"]
